services:
  mysql:
    image: mysql:latest
    container_name: mysql_products
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products_db
    volumes:
      - mysql_products_data:/var/lib/mysql
    
  app:
    build: .
    container_name: app_products
    restart: on-failure
    depends_on:  
      - mysql
    ports:
      - "8082:8082"
    environment:
      -SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/productos_db?createDatabaseIfNotExist=true
      -SPRING_DATASOURCE_USERNAME=root
      -SPRING_DATASOURCE_PASSWORD=root
volumes:
  mysql_products_data: